mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=springuser
    - MYSQL_PASSWORD=timao
    - MYSQL_DATABASE=product
    - MYSQL_ROOT_PASSWORD=root
